export class ThemeNeutralColors {
    constructor(
        public windowButtonIcon: string,
        public hoveredItemBackground: string,
        public selectedItemBackground: string,
        public tabText: string,
        public selectedTabText: string,
        public mainBackground: string,
        public headerBackground: string,
        public footerBackground: string,
        public sidePaneBackground: string,
        public primaryText: string,
        public secondaryText: string,
        public breadcrumbBackground: string,
        public sliderBackground: string,
        public sliderThumbBackground: string,
        public albumCoverLogo: string,
        public albumCoverBackground: string,
        public paneSeparators: string,
        public settingsSeparators: string,
        public contextMenuSeparators: string,
        public scrollBars: string,
        public searchBox: string,
        public searchBoxText: string,
        public searchBoxIcon: string,
        public dialogBackground: string,
        public primaryButtonText: string,
        public secondaryButtonBackground: string,
        public secondaryButtonText: string,
        public tooltipText: string
    ) {}
}
