/**
 * MPEG-4 audio object types as defined in https://wiki.multimedia.cx/index.php/MPEG-4_Audio#Audio_Object_Types .
 * Index corresponds to the value of the object type.
 */
export default [
    "Null",
    "AAC Main",
    "AAC LC (Low Complexity)",
    "AAC SSR (Scalable Sample Rate)",
    "AAC LTP (Long-Term Prediction)",
    "SBR (Spectral Band Replication)",
    "AAC Scalable",
    "TwinVQ",
    "CELP (Code Excited Linear Prediction)",
    "HXVC (Harmonic Vector eXcitation Coding)",
    "Reserved",
    "Reserved",
    "TTSI (Text-To-Speech Interface)",
    "Main Synthesis",
    "Wavetable Synthesis",
    "General MIDI",
    "Algorithmic Synthesis and Audio Effects",
    "Error Resilient AAC LC (Low Complexity)",
    "Reserved",
    "Error Resilient AAC LTP (Long-Term Prediction)",
    "Error Resilient AAC Scalable",
    "Error Resilient TwinVQ",
    "Error Resilient BSAC (Bit-Sliced Arithmetic Coding)",
    "Error Resilient AAC LD (Low Delay)",
    "Error Resilient CELP (Code Excited Linear Prediction)",
    "Error Resilient HXVC (Harmonic Vector eXcitation Coding)",
    "Error Resilient HILN (Harmonic and Individual Lines plus Noise)",
    "Error Resilient Parametric",
    "SSC (SinuSoidal Coding)",
    "PS (Parametric Stereo)",
    "MPEG Surround",
    "(escape value)",
    "Layer-1",
    "Layer-2",
    "Layer-3",
    "DST (Direct Stream Transfer)",
    "ALS (Audio Lossless)",
    "SLS (Scalable Lossless)",
    "SLS non-core",
    "Error Resilient AAC ELD (Enhanced Low Delay)",
    "SMR (Symbolic Music Representation) Simple",
    "SMR (Symbolic Music Representation) Main",
    "USAC (Unified Speech and Audio Coding) (no SBR)",
    "SAOC (Spatial Audio Object Coding)",
    "Low Delay MPEG Surround",
    "USAC (Unified Speech and Audio Coding)"
];
